name: Test on Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,docs]

      # - name: Check formatting with yapf
        # run: |
        #  yapf --diff --recursive --exit-code src test mechanisms examples setup.py docs/conf.py

      # - name: Lint with pylint
        # run: |
        #  pylint src test mechanisms examples setup.py docs/conf.py

      # - name: Check docstrings with pydocstyle
        #run: |
        #  pydocstyle src test mechanisms examples setup.py docs/conf.py

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:src/" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest test/*.py

      - name: Doc tests
        run: |
          pytest --doctest-modules src/mbi/*.py
  
      - name: Type checking
        run: |
          pytype src/mbi/*.py
